### ISSUE TITLE
prettier:ci errors during CodeBuild build phase

### ISSUE THREAD

**Issue by lepidotteri** [erezrokah/serverless-monitoring-app#43]
I followed your tutorial here: https://lumigo.io/blog/advanced-serverless-cicd-part-1-aws-codebuild/

If I push to master, then I will get the following error (in different workspaces each time) during the BUILD phase:
`COMMAND_EXECUTION_ERROR: Error while executing command: yarn prettier:ci. Reason: exit status 1`

from CodeBuild job logs:
```
lerna ERR! yarn run prettier:ci exited 1 in 'monitoring-tester-service' 
lerna ERR! yarn run prettier:ci stdout:

OR

lerna ERR! yarn run prettier:ci exited 1 in 'frontend' 
lerna ERR! yarn run prettier:ci stdout: 
```

**Comment by erezrokah** [comment]
Hey @lepidotteri can you try running `yarn prettier` before in your local dev environment. 
The error from CodeBuild means some files are not formatted.

**Comment by erezrokah** [comment]
Can you try again with my latest commit https://github.com/erezrokah/serverless-monitoring-app/commit/fdbb7f134872cb9c7a2b26521d83e2834fdf9cf1 ?

**Comment by lepidotteri** [comment]
![Schermata 2019-10-28 20:28:46](https://user-images.githubusercontent.com/45174270/67711121-98425880-f9c1-11e9-9b19-888c8c64bf3c.png)

**Comment by erezrokah** [comment]
I should have mentioned you should try running `yarn prettier` locally first again (if you hadn't)

**Comment by lepidotteri** [comment]
> I should have mentioned you should try running `yarn prettier` locally first again (if you hadn't)

I did actually, same behavior

**Comment by erezrokah** [comment]
What image are you using for the build? And what is your dev environment? maybe it is a line break issue

**Comment by lepidotteri** [comment]
> What image are you using for the build? And what is your dev environment? maybe it is a line break issue

image: aws/codebuild/standard:2.0
local: Debian Buster

**Comment by erezrokah** [comment]
I would try and copy some of the files that are failing prettier during build process (maybe publish them as build artifacts or even just copy them to an s3 bucket) and then compare with the files in the repo.

**Comment by lepidotteri** [comment]
> I would try and copy some of the files that are failing prettier during build process (maybe publish them as build artifacts or even just copy them to an s3 bucket) and then compare with the files in the repo.

already done that though.. SHA(s) match

**Comment by erezrokah** [comment]
How about running `yarn prettier` in CI then copy the modified files and comparing them?
