### ISSUE TITLE
Unresolved resource dependencies after deploy

### ISSUE THREAD

**Issue by lepidotteri** [erezrokah/serverless-monitoring-app#44]
If I try to deploy a dev environment, serverless gives this error for the third service: the tester-service (the first two are successful)

`  Error: The CloudFormation template is invalid: Unresolved resource dependencies [MonitoringDashtesterDashcheckDashendpointDashstepDashfunctionDashdev] in the Outputs block of the template
`

**Comment by lepidotteri** [comment]
Can you help on this?

**Comment by erezrokah** [comment]
I've been with a cold for the past two days. I'll try to reproduce later on this week

**Comment by erezrokah** [comment]
I've tried a full re-deploy with updated dependencies (https://github.com/erezrokah/serverless-monitoring-app/pull/47) and couldn't reproduce.
What command are you running to perform the deploy? and from which directory?
Do you mind sharing your repo? Or are you using an exact clone of this one?
Can you share the content of `services/monitoring-common/environment/config.dev.json` on your local machine?

I would also try deploying each service individually  `common->appsync->tester->frontend` by running `yarn deploy` from each service directory.

**Comment by lepidotteri** [comment]
thank you for taking the time to follow through on this Erez; I had also tried to update all dependencies; I will try seeing what happens when deployed individually; and yes, it's an exact clone with the updated dependencies so I must have screwed up something there (WebStorm was showing some missing dev dependencies for a couple of lerna sub packages in the tester service, and some errors for 1 e2e test related to the step functions with your aws-testing-library; but maybe this is all normal and expected).

Now, besides all this, I wanted to ask whether you are considering taking on new projects (you personally, and ideally start towards the end of next week or so). @blockchain-italia has a fairly small (good budget though), but interesting (blockchain-related) project ongoing that, judging from your community work (blog posts, stackoverflow, repos) + your background and expertise focus (advanced serverless projects and aspects: cicd, acceptance testing, etc.), you would be an essentially perfect fit for.

Ofc, here it's not the appropriate place to elaborate further so if you can get back to me on Keybase (I PM'ed you already) or somewhere, tomorrow, if you are up for it, I will try to write up a comprehensive document to onboard you quickly and explain exactly what we would need

**Comment by erezrokah** [comment]
Hey @lepidotteri thank you for the kind words. I've recently started a full time job with Netlify so I have very limited available time (as you must have noticed).
Regardless I would love to hear about your project so please do send me more information about it on keybase.

Furthermore, let's keep the discussion about the issue relevant to the issue itself ;)
